/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.targeting.report.campaign.tracking.action.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.content.targeting.report.campaign.tracking.action.model.CTAction;
import com.liferay.content.targeting.report.campaign.tracking.action.service.CTActionLocalService;
import com.liferay.content.targeting.report.campaign.tracking.action.service.persistence.CTActionFinder;
import com.liferay.content.targeting.report.campaign.tracking.action.service.persistence.CTActionPersistence;
import com.liferay.content.targeting.report.campaign.tracking.action.service.persistence.CTActionTotalFinder;
import com.liferay.content.targeting.report.campaign.tracking.action.service.persistence.CTActionTotalPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the c t action local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.content.targeting.report.campaign.tracking.action.service.impl.CTActionLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.content.targeting.report.campaign.tracking.action.service.impl.CTActionLocalServiceImpl
 * @see com.liferay.content.targeting.report.campaign.tracking.action.service.CTActionLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class CTActionLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements CTActionLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.content.targeting.report.campaign.tracking.action.service.CTActionLocalServiceUtil} to access the c t action local service.
	 */

	/**
	 * Adds the c t action to the database. Also notifies the appropriate model listeners.
	 *
	 * @param ctAction the c t action
	 * @return the c t action that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CTAction addCTAction(CTAction ctAction) {
		ctAction.setNew(true);

		return ctActionPersistence.update(ctAction);
	}

	/**
	 * Creates a new c t action with the primary key. Does not add the c t action to the database.
	 *
	 * @param CTActionId the primary key for the new c t action
	 * @return the new c t action
	 */
	@Override
	public CTAction createCTAction(long CTActionId) {
		return ctActionPersistence.create(CTActionId);
	}

	/**
	 * Deletes the c t action with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param CTActionId the primary key of the c t action
	 * @return the c t action that was removed
	 * @throws PortalException if a c t action with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CTAction deleteCTAction(long CTActionId) throws PortalException {
		return ctActionPersistence.remove(CTActionId);
	}

	/**
	 * Deletes the c t action from the database. Also notifies the appropriate model listeners.
	 *
	 * @param ctAction the c t action
	 * @return the c t action that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CTAction deleteCTAction(CTAction ctAction) {
		return ctActionPersistence.remove(ctAction);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(CTAction.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return ctActionPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.content.targeting.report.campaign.tracking.action.model.impl.CTActionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return ctActionPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.content.targeting.report.campaign.tracking.action.model.impl.CTActionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return ctActionPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return ctActionPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return ctActionPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public CTAction fetchCTAction(long CTActionId) {
		return ctActionPersistence.fetchByPrimaryKey(CTActionId);
	}

	/**
	 * Returns the c t action with the primary key.
	 *
	 * @param CTActionId the primary key of the c t action
	 * @return the c t action
	 * @throws PortalException if a c t action with the primary key could not be found
	 */
	@Override
	public CTAction getCTAction(long CTActionId) throws PortalException {
		return ctActionPersistence.findByPrimaryKey(CTActionId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(com.liferay.content.targeting.report.campaign.tracking.action.service.CTActionLocalServiceUtil.getService());
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CTAction.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("CTActionId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(com.liferay.content.targeting.report.campaign.tracking.action.service.CTActionLocalServiceUtil.getService());
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(CTAction.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("CTActionId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(com.liferay.content.targeting.report.campaign.tracking.action.service.CTActionLocalServiceUtil.getService());
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CTAction.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("CTActionId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return ctActionLocalService.deleteCTAction((CTAction)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return ctActionPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the c t actions.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.content.targeting.report.campaign.tracking.action.model.impl.CTActionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of c t actions
	 * @param end the upper bound of the range of c t actions (not inclusive)
	 * @return the range of c t actions
	 */
	@Override
	public List<CTAction> getCTActions(int start, int end) {
		return ctActionPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of c t actions.
	 *
	 * @return the number of c t actions
	 */
	@Override
	public int getCTActionsCount() {
		return ctActionPersistence.countAll();
	}

	/**
	 * Updates the c t action in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param ctAction the c t action
	 * @return the c t action that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CTAction updateCTAction(CTAction ctAction) {
		return ctActionPersistence.update(ctAction);
	}

	/**
	 * Returns the c t action local service.
	 *
	 * @return the c t action local service
	 */
	public CTActionLocalService getCTActionLocalService() {
		return ctActionLocalService;
	}

	/**
	 * Sets the c t action local service.
	 *
	 * @param ctActionLocalService the c t action local service
	 */
	public void setCTActionLocalService(
		CTActionLocalService ctActionLocalService) {
		this.ctActionLocalService = ctActionLocalService;
	}

	/**
	 * Returns the c t action persistence.
	 *
	 * @return the c t action persistence
	 */
	public CTActionPersistence getCTActionPersistence() {
		return ctActionPersistence;
	}

	/**
	 * Sets the c t action persistence.
	 *
	 * @param ctActionPersistence the c t action persistence
	 */
	public void setCTActionPersistence(CTActionPersistence ctActionPersistence) {
		this.ctActionPersistence = ctActionPersistence;
	}

	/**
	 * Returns the c t action finder.
	 *
	 * @return the c t action finder
	 */
	public CTActionFinder getCTActionFinder() {
		return ctActionFinder;
	}

	/**
	 * Sets the c t action finder.
	 *
	 * @param ctActionFinder the c t action finder
	 */
	public void setCTActionFinder(CTActionFinder ctActionFinder) {
		this.ctActionFinder = ctActionFinder;
	}

	/**
	 * Returns the c t action total local service.
	 *
	 * @return the c t action total local service
	 */
	public com.liferay.content.targeting.report.campaign.tracking.action.service.CTActionTotalLocalService getCTActionTotalLocalService() {
		return ctActionTotalLocalService;
	}

	/**
	 * Sets the c t action total local service.
	 *
	 * @param ctActionTotalLocalService the c t action total local service
	 */
	public void setCTActionTotalLocalService(
		com.liferay.content.targeting.report.campaign.tracking.action.service.CTActionTotalLocalService ctActionTotalLocalService) {
		this.ctActionTotalLocalService = ctActionTotalLocalService;
	}

	/**
	 * Returns the c t action total persistence.
	 *
	 * @return the c t action total persistence
	 */
	public CTActionTotalPersistence getCTActionTotalPersistence() {
		return ctActionTotalPersistence;
	}

	/**
	 * Sets the c t action total persistence.
	 *
	 * @param ctActionTotalPersistence the c t action total persistence
	 */
	public void setCTActionTotalPersistence(
		CTActionTotalPersistence ctActionTotalPersistence) {
		this.ctActionTotalPersistence = ctActionTotalPersistence;
	}

	/**
	 * Returns the c t action total finder.
	 *
	 * @return the c t action total finder
	 */
	public CTActionTotalFinder getCTActionTotalFinder() {
		return ctActionTotalFinder;
	}

	/**
	 * Sets the c t action total finder.
	 *
	 * @param ctActionTotalFinder the c t action total finder
	 */
	public void setCTActionTotalFinder(CTActionTotalFinder ctActionTotalFinder) {
		this.ctActionTotalFinder = ctActionTotalFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.content.targeting.report.campaign.tracking.action.model.CTAction",
			ctActionLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.content.targeting.report.campaign.tracking.action.model.CTAction");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CTActionLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CTAction.class;
	}

	protected String getModelClassName() {
		return CTAction.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = ctActionPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.content.targeting.report.campaign.tracking.action.service.CTActionLocalService.class)
	protected CTActionLocalService ctActionLocalService;
	@BeanReference(type = CTActionPersistence.class)
	protected CTActionPersistence ctActionPersistence;
	@BeanReference(type = CTActionFinder.class)
	protected CTActionFinder ctActionFinder;
	@BeanReference(type = com.liferay.content.targeting.report.campaign.tracking.action.service.CTActionTotalLocalService.class)
	protected com.liferay.content.targeting.report.campaign.tracking.action.service.CTActionTotalLocalService ctActionTotalLocalService;
	@BeanReference(type = CTActionTotalPersistence.class)
	protected CTActionTotalPersistence ctActionTotalPersistence;
	@BeanReference(type = CTActionTotalFinder.class)
	protected CTActionTotalFinder ctActionTotalFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}