/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.geolocation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Geolocation service. Represents a row in the &quot;GEO_Geolocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.geolocation.model.impl.GeolocationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.geolocation.model.impl.GeolocationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Geolocation
 * @see com.liferay.geolocation.model.impl.GeolocationImpl
 * @see com.liferay.geolocation.model.impl.GeolocationModelImpl
 * @generated
 */
public interface GeolocationModel extends AttachedModel, BaseModel<Geolocation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a geolocation model instance should use the {@link Geolocation} interface instead.
	 */

	/**
	 * Returns the primary key of this geolocation.
	 *
	 * @return the primary key of this geolocation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this geolocation.
	 *
	 * @param primaryKey the primary key of this geolocation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this geolocation.
	 *
	 * @return the uuid of this geolocation
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this geolocation.
	 *
	 * @param uuid the uuid of this geolocation
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the geolocation ID of this geolocation.
	 *
	 * @return the geolocation ID of this geolocation
	 */
	public long getGeolocationId();

	/**
	 * Sets the geolocation ID of this geolocation.
	 *
	 * @param geolocationId the geolocation ID of this geolocation
	 */
	public void setGeolocationId(long geolocationId);

	/**
	 * Returns the company ID of this geolocation.
	 *
	 * @return the company ID of this geolocation
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this geolocation.
	 *
	 * @param companyId the company ID of this geolocation
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the modified date of this geolocation.
	 *
	 * @return the modified date of this geolocation
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this geolocation.
	 *
	 * @param modifiedDate the modified date of this geolocation
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this geolocation.
	 *
	 * @return the fully qualified class name of this geolocation
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this geolocation.
	 *
	 * @return the class name ID of this geolocation
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this geolocation.
	 *
	 * @param classNameId the class name ID of this geolocation
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this geolocation.
	 *
	 * @return the class p k of this geolocation
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this geolocation.
	 *
	 * @param classPK the class p k of this geolocation
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the latitude of this geolocation.
	 *
	 * @return the latitude of this geolocation
	 */
	public double getLatitude();

	/**
	 * Sets the latitude of this geolocation.
	 *
	 * @param latitude the latitude of this geolocation
	 */
	public void setLatitude(double latitude);

	/**
	 * Returns the longitude of this geolocation.
	 *
	 * @return the longitude of this geolocation
	 */
	public double getLongitude();

	/**
	 * Sets the longitude of this geolocation.
	 *
	 * @param longitude the longitude of this geolocation
	 */
	public void setLongitude(double longitude);

	/**
	 * Returns the area code of this geolocation.
	 *
	 * @return the area code of this geolocation
	 */
	@AutoEscape
	public String getAreaCode();

	/**
	 * Sets the area code of this geolocation.
	 *
	 * @param areaCode the area code of this geolocation
	 */
	public void setAreaCode(String areaCode);

	/**
	 * Returns the city of this geolocation.
	 *
	 * @return the city of this geolocation
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this geolocation.
	 *
	 * @param city the city of this geolocation
	 */
	public void setCity(String city);

	/**
	 * Returns the country code of this geolocation.
	 *
	 * @return the country code of this geolocation
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this geolocation.
	 *
	 * @param countryCode the country code of this geolocation
	 */
	public void setCountryCode(String countryCode);

	/**
	 * Returns the country name of this geolocation.
	 *
	 * @return the country name of this geolocation
	 */
	@AutoEscape
	public String getCountryName();

	/**
	 * Sets the country name of this geolocation.
	 *
	 * @param countryName the country name of this geolocation
	 */
	public void setCountryName(String countryName);

	/**
	 * Returns the metro code of this geolocation.
	 *
	 * @return the metro code of this geolocation
	 */
	@AutoEscape
	public String getMetroCode();

	/**
	 * Sets the metro code of this geolocation.
	 *
	 * @param metroCode the metro code of this geolocation
	 */
	public void setMetroCode(String metroCode);

	/**
	 * Returns the region code of this geolocation.
	 *
	 * @return the region code of this geolocation
	 */
	@AutoEscape
	public String getRegionCode();

	/**
	 * Sets the region code of this geolocation.
	 *
	 * @param regionCode the region code of this geolocation
	 */
	public void setRegionCode(String regionCode);

	/**
	 * Returns the region name of this geolocation.
	 *
	 * @return the region name of this geolocation
	 */
	@AutoEscape
	public String getRegionName();

	/**
	 * Sets the region name of this geolocation.
	 *
	 * @param regionName the region name of this geolocation
	 */
	public void setRegionName(String regionName);

	/**
	 * Returns the zip code of this geolocation.
	 *
	 * @return the zip code of this geolocation
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this geolocation.
	 *
	 * @param zipCode the zip code of this geolocation
	 */
	public void setZipCode(String zipCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Geolocation geolocation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Geolocation> toCacheModel();

	@Override
	public Geolocation toEscapedModel();

	@Override
	public Geolocation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}