/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.targeting.rule.engine.service.base;

import com.liferay.content.targeting.rule.engine.model.RuleEngine;
import com.liferay.content.targeting.rule.engine.service.RuleEngineService;
import com.liferay.content.targeting.rule.engine.service.persistence.RuleEnginePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the rule engine remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.content.targeting.rule.engine.service.impl.RuleEngineServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.content.targeting.rule.engine.service.impl.RuleEngineServiceImpl
 * @see com.liferay.content.targeting.rule.engine.service.RuleEngineServiceUtil
 * @generated
 */
public abstract class RuleEngineServiceBaseImpl extends BaseServiceImpl
	implements RuleEngineService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.content.targeting.rule.engine.service.RuleEngineServiceUtil} to access the rule engine remote service.
	 */

	/**
	 * Returns the rule engine local service.
	 *
	 * @return the rule engine local service
	 */
	public com.liferay.content.targeting.rule.engine.service.RuleEngineLocalService getRuleEngineLocalService() {
		return ruleEngineLocalService;
	}

	/**
	 * Sets the rule engine local service.
	 *
	 * @param ruleEngineLocalService the rule engine local service
	 */
	public void setRuleEngineLocalService(
		com.liferay.content.targeting.rule.engine.service.RuleEngineLocalService ruleEngineLocalService) {
		this.ruleEngineLocalService = ruleEngineLocalService;
	}

	/**
	 * Returns the rule engine remote service.
	 *
	 * @return the rule engine remote service
	 */
	public com.liferay.content.targeting.rule.engine.service.RuleEngineService getRuleEngineService() {
		return ruleEngineService;
	}

	/**
	 * Sets the rule engine remote service.
	 *
	 * @param ruleEngineService the rule engine remote service
	 */
	public void setRuleEngineService(
		com.liferay.content.targeting.rule.engine.service.RuleEngineService ruleEngineService) {
		this.ruleEngineService = ruleEngineService;
	}

	/**
	 * Returns the rule engine persistence.
	 *
	 * @return the rule engine persistence
	 */
	public RuleEnginePersistence getRuleEnginePersistence() {
		return ruleEnginePersistence;
	}

	/**
	 * Sets the rule engine persistence.
	 *
	 * @param ruleEnginePersistence the rule engine persistence
	 */
	public void setRuleEnginePersistence(
		RuleEnginePersistence ruleEnginePersistence) {
		this.ruleEnginePersistence = ruleEnginePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return RuleEngine.class;
	}

	protected String getModelClassName() {
		return RuleEngine.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = ruleEnginePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.content.targeting.rule.engine.service.RuleEngineLocalService.class)
	protected com.liferay.content.targeting.rule.engine.service.RuleEngineLocalService ruleEngineLocalService;
	@BeanReference(type = com.liferay.content.targeting.rule.engine.service.RuleEngineService.class)
	protected com.liferay.content.targeting.rule.engine.service.RuleEngineService ruleEngineService;
	@BeanReference(type = RuleEnginePersistence.class)
	protected RuleEnginePersistence ruleEnginePersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private RuleEngineServiceClpInvoker _clpInvoker = new RuleEngineServiceClpInvoker();
}