/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.targeting.rule.engine.service.base;

import com.liferay.content.targeting.rule.engine.model.RuleEngine;
import com.liferay.content.targeting.rule.engine.service.RuleEngineLocalService;
import com.liferay.content.targeting.rule.engine.service.persistence.RuleEnginePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the rule engine local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.content.targeting.rule.engine.service.impl.RuleEngineLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.content.targeting.rule.engine.service.impl.RuleEngineLocalServiceImpl
 * @see com.liferay.content.targeting.rule.engine.service.RuleEngineLocalServiceUtil
 * @generated
 */
public abstract class RuleEngineLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements RuleEngineLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.content.targeting.rule.engine.service.RuleEngineLocalServiceUtil} to access the rule engine local service.
	 */

	/**
	 * Adds the rule engine to the database. Also notifies the appropriate model listeners.
	 *
	 * @param ruleEngine the rule engine
	 * @return the rule engine that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RuleEngine addRuleEngine(RuleEngine ruleEngine)
		throws SystemException {
		ruleEngine.setNew(true);

		return ruleEnginePersistence.update(ruleEngine);
	}

	/**
	 * Creates a new rule engine with the primary key. Does not add the rule engine to the database.
	 *
	 * @param dummyId the primary key for the new rule engine
	 * @return the new rule engine
	 */
	@Override
	public RuleEngine createRuleEngine(long dummyId) {
		return ruleEnginePersistence.create(dummyId);
	}

	/**
	 * Deletes the rule engine with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param dummyId the primary key of the rule engine
	 * @return the rule engine that was removed
	 * @throws PortalException if a rule engine with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RuleEngine deleteRuleEngine(long dummyId)
		throws PortalException, SystemException {
		return ruleEnginePersistence.remove(dummyId);
	}

	/**
	 * Deletes the rule engine from the database. Also notifies the appropriate model listeners.
	 *
	 * @param ruleEngine the rule engine
	 * @return the rule engine that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RuleEngine deleteRuleEngine(RuleEngine ruleEngine)
		throws SystemException {
		return ruleEnginePersistence.remove(ruleEngine);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(RuleEngine.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return ruleEnginePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.content.targeting.rule.engine.model.impl.RuleEngineModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return ruleEnginePersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.content.targeting.rule.engine.model.impl.RuleEngineModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return ruleEnginePersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return ruleEnginePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return ruleEnginePersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public RuleEngine fetchRuleEngine(long dummyId) throws SystemException {
		return ruleEnginePersistence.fetchByPrimaryKey(dummyId);
	}

	/**
	 * Returns the rule engine with the primary key.
	 *
	 * @param dummyId the primary key of the rule engine
	 * @return the rule engine
	 * @throws PortalException if a rule engine with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public RuleEngine getRuleEngine(long dummyId)
		throws PortalException, SystemException {
		return ruleEnginePersistence.findByPrimaryKey(dummyId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return ruleEnginePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the rule engines.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.content.targeting.rule.engine.model.impl.RuleEngineModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of rule engines
	 * @param end the upper bound of the range of rule engines (not inclusive)
	 * @return the range of rule engines
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<RuleEngine> getRuleEngines(int start, int end)
		throws SystemException {
		return ruleEnginePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of rule engines.
	 *
	 * @return the number of rule engines
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getRuleEnginesCount() throws SystemException {
		return ruleEnginePersistence.countAll();
	}

	/**
	 * Updates the rule engine in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param ruleEngine the rule engine
	 * @return the rule engine that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RuleEngine updateRuleEngine(RuleEngine ruleEngine)
		throws SystemException {
		return ruleEnginePersistence.update(ruleEngine);
	}

	/**
	 * Returns the rule engine local service.
	 *
	 * @return the rule engine local service
	 */
	public com.liferay.content.targeting.rule.engine.service.RuleEngineLocalService getRuleEngineLocalService() {
		return ruleEngineLocalService;
	}

	/**
	 * Sets the rule engine local service.
	 *
	 * @param ruleEngineLocalService the rule engine local service
	 */
	public void setRuleEngineLocalService(
		com.liferay.content.targeting.rule.engine.service.RuleEngineLocalService ruleEngineLocalService) {
		this.ruleEngineLocalService = ruleEngineLocalService;
	}

	/**
	 * Returns the rule engine remote service.
	 *
	 * @return the rule engine remote service
	 */
	public com.liferay.content.targeting.rule.engine.service.RuleEngineService getRuleEngineService() {
		return ruleEngineService;
	}

	/**
	 * Sets the rule engine remote service.
	 *
	 * @param ruleEngineService the rule engine remote service
	 */
	public void setRuleEngineService(
		com.liferay.content.targeting.rule.engine.service.RuleEngineService ruleEngineService) {
		this.ruleEngineService = ruleEngineService;
	}

	/**
	 * Returns the rule engine persistence.
	 *
	 * @return the rule engine persistence
	 */
	public RuleEnginePersistence getRuleEnginePersistence() {
		return ruleEnginePersistence;
	}

	/**
	 * Sets the rule engine persistence.
	 *
	 * @param ruleEnginePersistence the rule engine persistence
	 */
	public void setRuleEnginePersistence(
		RuleEnginePersistence ruleEnginePersistence) {
		this.ruleEnginePersistence = ruleEnginePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.liferay.content.targeting.rule.engine.model.RuleEngine",
			ruleEngineLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.liferay.content.targeting.rule.engine.model.RuleEngine");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return RuleEngine.class;
	}

	protected String getModelClassName() {
		return RuleEngine.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = ruleEnginePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.content.targeting.rule.engine.service.RuleEngineLocalService.class)
	protected com.liferay.content.targeting.rule.engine.service.RuleEngineLocalService ruleEngineLocalService;
	@BeanReference(type = com.liferay.content.targeting.rule.engine.service.RuleEngineService.class)
	protected com.liferay.content.targeting.rule.engine.service.RuleEngineService ruleEngineService;
	@BeanReference(type = RuleEnginePersistence.class)
	protected RuleEnginePersistence ruleEnginePersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private RuleEngineLocalServiceClpInvoker _clpInvoker = new RuleEngineLocalServiceClpInvoker();
}