/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.targeting.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ReportInstance service. Represents a row in the &quot;CT_ReportInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.content.targeting.model.impl.ReportInstanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.content.targeting.model.impl.ReportInstanceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReportInstance
 * @see com.liferay.content.targeting.model.impl.ReportInstanceImpl
 * @see com.liferay.content.targeting.model.impl.ReportInstanceModelImpl
 * @generated
 */
public interface ReportInstanceModel extends BaseModel<ReportInstance> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a report instance model instance should use the {@link ReportInstance} interface instead.
	 */

	/**
	 * Returns the primary key of this report instance.
	 *
	 * @return the primary key of this report instance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this report instance.
	 *
	 * @param primaryKey the primary key of this report instance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the report instance ID of this report instance.
	 *
	 * @return the report instance ID of this report instance
	 */
	public long getReportInstanceId();

	/**
	 * Sets the report instance ID of this report instance.
	 *
	 * @param reportInstanceId the report instance ID of this report instance
	 */
	public void setReportInstanceId(long reportInstanceId);

	/**
	 * Returns the group ID of this report instance.
	 *
	 * @return the group ID of this report instance
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this report instance.
	 *
	 * @param groupId the group ID of this report instance
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this report instance.
	 *
	 * @return the company ID of this report instance
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this report instance.
	 *
	 * @param companyId the company ID of this report instance
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this report instance.
	 *
	 * @return the user ID of this report instance
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this report instance.
	 *
	 * @param userId the user ID of this report instance
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this report instance.
	 *
	 * @return the user uuid of this report instance
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this report instance.
	 *
	 * @param userUuid the user uuid of this report instance
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this report instance.
	 *
	 * @return the user name of this report instance
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this report instance.
	 *
	 * @param userName the user name of this report instance
	 */
	public void setUserName(String userName);

	/**
	 * Returns the modified date of this report instance.
	 *
	 * @return the modified date of this report instance
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this report instance.
	 *
	 * @param modifiedDate the modified date of this report instance
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the report key of this report instance.
	 *
	 * @return the report key of this report instance
	 */
	@AutoEscape
	public String getReportKey();

	/**
	 * Sets the report key of this report instance.
	 *
	 * @param reportKey the report key of this report instance
	 */
	public void setReportKey(String reportKey);

	/**
	 * Returns the class name of this report instance.
	 *
	 * @return the class name of this report instance
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this report instance.
	 *
	 * @param className the class name of this report instance
	 */
	public void setClassName(String className);

	/**
	 * Returns the class p k of this report instance.
	 *
	 * @return the class p k of this report instance
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this report instance.
	 *
	 * @param classPK the class p k of this report instance
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the type settings of this report instance.
	 *
	 * @return the type settings of this report instance
	 */
	@AutoEscape
	public String getTypeSettings();

	/**
	 * Sets the type settings of this report instance.
	 *
	 * @param typeSettings the type settings of this report instance
	 */
	public void setTypeSettings(String typeSettings);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ReportInstance reportInstance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ReportInstance> toCacheModel();

	@Override
	public ReportInstance toEscapedModel();

	@Override
	public ReportInstance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}