create index IX_B22F5BC9 on ContentTargeting_CampaignTrackingActionReport_CampaignTrackingAction (campaignId);
create index IX_58ADA254 on ContentTargeting_CampaignTrackingActionReport_CampaignTrackingAction (campaignId, modifiedDate);
create index IX_5AB8CC52 on ContentTargeting_CampaignTrackingActionReport_CampaignTrackingAction (campaignId, userSegmentId, plid, elementId, eventType);