/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.contenttargeting.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CTUser service. Represents a row in the &quot;CT_CTUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.contenttargeting.model.impl.CTUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.contenttargeting.model.impl.CTUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CTUser
 * @see com.liferay.contenttargeting.model.impl.CTUserImpl
 * @see com.liferay.contenttargeting.model.impl.CTUserModelImpl
 * @generated
 */
public interface CTUserModel extends BaseModel<CTUser>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c t user model instance should use the {@link CTUser} interface instead.
	 */

	/**
	 * Returns the primary key of this c t user.
	 *
	 * @return the primary key of this c t user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this c t user.
	 *
	 * @param primaryKey the primary key of this c t user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this c t user.
	 *
	 * @return the uuid of this c t user
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this c t user.
	 *
	 * @param uuid the uuid of this c t user
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the c t user ID of this c t user.
	 *
	 * @return the c t user ID of this c t user
	 */
	public long getCTUserId();

	/**
	 * Sets the c t user ID of this c t user.
	 *
	 * @param CTUserId the c t user ID of this c t user
	 */
	public void setCTUserId(long CTUserId);

	/**
	 * Returns the c t user uuid of this c t user.
	 *
	 * @return the c t user uuid of this c t user
	 * @throws SystemException if a system exception occurred
	 */
	public String getCTUserUuid() throws SystemException;

	/**
	 * Sets the c t user uuid of this c t user.
	 *
	 * @param CTUserUuid the c t user uuid of this c t user
	 */
	public void setCTUserUuid(String CTUserUuid);

	/**
	 * Returns the group ID of this c t user.
	 *
	 * @return the group ID of this c t user
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this c t user.
	 *
	 * @param groupId the group ID of this c t user
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this c t user.
	 *
	 * @return the company ID of this c t user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this c t user.
	 *
	 * @param companyId the company ID of this c t user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this c t user.
	 *
	 * @return the user ID of this c t user
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this c t user.
	 *
	 * @param userId the user ID of this c t user
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this c t user.
	 *
	 * @return the user uuid of this c t user
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this c t user.
	 *
	 * @param userUuid the user uuid of this c t user
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this c t user.
	 *
	 * @return the user name of this c t user
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this c t user.
	 *
	 * @param userName the user name of this c t user
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this c t user.
	 *
	 * @return the create date of this c t user
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this c t user.
	 *
	 * @param createDate the create date of this c t user
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this c t user.
	 *
	 * @return the modified date of this c t user
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this c t user.
	 *
	 * @param modifiedDate the modified date of this c t user
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the last ip of this c t user.
	 *
	 * @return the last ip of this c t user
	 */
	@AutoEscape
	public String getLastIp();

	/**
	 * Sets the last ip of this c t user.
	 *
	 * @param lastIp the last ip of this c t user
	 */
	public void setLastIp(String lastIp);

	/**
	 * Returns the type settings of this c t user.
	 *
	 * @return the type settings of this c t user
	 */
	@AutoEscape
	public String getTypeSettings();

	/**
	 * Sets the type settings of this c t user.
	 *
	 * @param typeSettings the type settings of this c t user
	 */
	public void setTypeSettings(String typeSettings);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CTUser ctUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CTUser> toCacheModel();

	@Override
	public CTUser toEscapedModel();

	@Override
	public CTUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}