/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.targeting.rule.score.points.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ScorePoint service. Represents a row in the &quot;CT_ScorePoints_ScorePoint&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.content.targeting.rule.score.points.model.impl.ScorePointModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.content.targeting.rule.score.points.model.impl.ScorePointImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ScorePoint
 * @see com.liferay.content.targeting.rule.score.points.model.impl.ScorePointImpl
 * @see com.liferay.content.targeting.rule.score.points.model.impl.ScorePointModelImpl
 * @generated
 */
public interface ScorePointModel extends BaseModel<ScorePoint> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a score point model instance should use the {@link ScorePoint} interface instead.
	 */

	/**
	 * Returns the primary key of this score point.
	 *
	 * @return the primary key of this score point
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this score point.
	 *
	 * @param primaryKey the primary key of this score point
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this score point.
	 *
	 * @return the uuid of this score point
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this score point.
	 *
	 * @param uuid the uuid of this score point
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the score point ID of this score point.
	 *
	 * @return the score point ID of this score point
	 */
	public long getScorePointId();

	/**
	 * Sets the score point ID of this score point.
	 *
	 * @param scorePointId the score point ID of this score point
	 */
	public void setScorePointId(long scorePointId);

	/**
	 * Returns the anonymous user ID of this score point.
	 *
	 * @return the anonymous user ID of this score point
	 */
	public long getAnonymousUserId();

	/**
	 * Sets the anonymous user ID of this score point.
	 *
	 * @param anonymousUserId the anonymous user ID of this score point
	 */
	public void setAnonymousUserId(long anonymousUserId);

	/**
	 * Returns the anonymous user uuid of this score point.
	 *
	 * @return the anonymous user uuid of this score point
	 * @throws SystemException if a system exception occurred
	 */
	public String getAnonymousUserUuid() throws SystemException;

	/**
	 * Sets the anonymous user uuid of this score point.
	 *
	 * @param anonymousUserUuid the anonymous user uuid of this score point
	 */
	public void setAnonymousUserUuid(String anonymousUserUuid);

	/**
	 * Returns the user segment ID of this score point.
	 *
	 * @return the user segment ID of this score point
	 */
	public long getUserSegmentId();

	/**
	 * Sets the user segment ID of this score point.
	 *
	 * @param userSegmentId the user segment ID of this score point
	 */
	public void setUserSegmentId(long userSegmentId);

	/**
	 * Returns the points of this score point.
	 *
	 * @return the points of this score point
	 */
	public long getPoints();

	/**
	 * Sets the points of this score point.
	 *
	 * @param points the points of this score point
	 */
	public void setPoints(long points);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ScorePoint scorePoint);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ScorePoint> toCacheModel();

	@Override
	public ScorePoint toEscapedModel();

	@Override
	public ScorePoint toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}