package com.liferay.consumer.manager.model.impl;

import com.liferay.consumer.manager.model.ConsumerExtensionInstance;
import com.liferay.consumer.manager.service.ConsumerExtensionInstanceLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ConsumerExtensionInstance service. Represents a row in the &quot;CM_ConsumerExtensionInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConsumerExtensionInstanceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConsumerExtensionInstanceImpl
 * @see com.liferay.consumer.manager.model.ConsumerExtensionInstance
 * @generated
 */
public abstract class ConsumerExtensionInstanceBaseImpl
    extends ConsumerExtensionInstanceModelImpl
    implements ConsumerExtensionInstance {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a consumer extension instance model instance should use the {@link ConsumerExtensionInstance} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ConsumerExtensionInstanceLocalServiceUtil.addConsumerExtensionInstance(this);
        } else {
            ConsumerExtensionInstanceLocalServiceUtil.updateConsumerExtensionInstance(this);
        }
    }
}
